//src/app/(app)/layout.tsx

import type { Metadata } from "next";
import '../globals.css'
import SideBar from "@/components/layout/SideBar";
import MobileNav from "@/components/layout/MobileNav";
import { auth } from "@/lib/auth-config";



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  const session = await auth();

  return (
  <div className="min-h-screen md:flex">
    <div className="hidden md:block">
      <SideBar user={session?.user} />
    </div>

    <div className="md:hidden">
      <MobileNav user={session?.user} />
    </div>

    <main className="min-w-0 flex-1">
      {children}
    </main>
  </div>
);
}
